--- 
title: "Practical Statistics for Data Scientists Book Club"
author: "The R4DS Online Learning Community"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: book.bib
biblio-style: apalike
link-citations: yes
github-repo: r4ds/bookclub-ps4ds
description: "This is the product of the R4DS Online Learning Community's Practical Statistics for Data Scientists Book Club."
---

# Welcome {-}

This is a companion for the book [_Practical Statistics for Data Scientists_](https://www.oreilly.com/library/view/practical-statistics-for/9781492072935/) by Peter Bruce, Andrew Bruce, and Peter Gedeck (O'Reilly, copyright 2020, 978-1-492-07294-2).
This companion is available at [r4ds.io/ps4ds](https://r4ds.io/ps4ds).

This website is being developed by the [R4DS Online Learning Community](https://rfordatasci.com). Follow along, and [join the community](https://r4ds.io/join) to participate.

This companion follows the [R4DS Online Learning Community Code of Conduct](https://r4ds.io/conduct).

## Book club meetings {-}

- Each week, a volunteer will present a chapter from the book (or part of a chapter).
  - **This is the best way to learn the material.**
- Presentations will usually consist of a review of the material, a discussion, and/or a demonstration of the principles presented in that chapter.
- More information about how to present is available in the [github repo](https://github.com/r4ds/bookclub-ps4ds).
- Presentations will be recorded, and will be available on the [R4DS Online Learning Community YouTube Channel](https://r4ds.io/youtube).

## Sample code {-}

Sample code is available at [github.com/gedeck/practical-statistics-for-data-scientists](https://github.com/gedeck/practical-statistics-for-data-scientists)

You can install all packages used by these notes and recommended by the book authors[^1]:

```{r install-book, eval = FALSE}
install.packages("remotes")
remotes::install_github("r4ds/bookclub-ps4ds")
remove.packages("ps4ds") # This isn't really a package.
```

[^1]: Chapter 5 uses {DMwR}, which is currently unavailable on CRAN. We'll confirm when we get there, but I'm guessing {DMwR2} will work instead.

## 1st edition vs 2nd edition {-}

Here we'll attempt to document differences between 1e and 2e.

- 2e added Python example code
- Some sections and subsections have slight name changes
- Chapter 1: New subsection in 1.6, "Probability"
- Chapter 2: New sections "Chi-Square Distribution" & "F-Distribution"
- Chapter 4: New subsection in 4.2, "Further Reading"
- Chapter 7: New subsection in 7.1, "Correspondence Analysis"

## Pace {-}

- Chapters are long, but not always dense.
- We'll _try_ to cover 1 chapter/week, but...
- ...It's ok to split chapters when they feel like too much.

## Meeting Videos

### Cohort 1

`r knitr::include_url("https://www.youtube.com/embed/yuFdAZvdyg8")`

<details>
<summary> Meeting chat log </summary>

```
00:12:31	Jon Harmon (jonthegeek):	r4ds.io/ps4ds
00:14:47	Bryan Tegomoh:	2nd edition
00:14:49	Scott Nestler:	I have a copy of each.
00:14:50	Francisco Escobar:	1e
00:17:26	Scott Nestler:	Sounds like a good plan to start with.
00:18:28	Kaytee Flick:	I liked that part:D
00:21:29	Jon Harmon (jonthegeek):	For those synching up later: "I liked that part" was about the Tukey stuff in chapter 1.
00:32:34	Diego Ramírez González:	I am a neuroscience grad student in Mexico. I am here to study stats :)
00:32:58	Kaytee Flick:	Yay neuroscience!
00:34:49	Morgan Grovenburg:	https://github.com/r4ds/bookclub-ps4ds
00:38:03	Kaytee Flick:	Can confirm that learning both simultaneously can break your brain....speaking from my current experience:P
00:38:22	shamsuddeen:	@Kaytee..-;)
```
</details>
